### ISSUE TITLE
Focus lost

### ISSUE THREAD

**Issue by rickardjanson** [dfilatov/vidom#59]
Let say you have created a virtual DOM tree, and want to trigger a event on a particular node in the tree.

How you do it?

Example "change" should be "triggered" each time you e.g. click / change it. And I can't find any use of `document.activeElement`, so the focus will be lost if you have 3 select and jumping from one to one?

**Comment by dfilatov** [comment]
please attach an example code to show the problem

**Comment by rickardjanson** [comment]
It's happen during updating the virtual tree. Best example describiing the issue is here: https://github.com/trackira/trackira#keys

Open the jsFiddle in webkit, click on an input box and see how it's jumping form one to another.. Changing focus.

**Comment by dfilatov** [comment]
Have you tried to do the same with vidom? Doesn't it work?

**Comment by rickardjanson** [comment]
I know this is a little tricky but happen when you update the virtual tree. As you see in his source he support also multiple trees to be mounted on same node. And he can update one or all node trees at once.

**Comment by rickardjanson** [comment]
It's not working because the children are not updated. See citojs solution too.

**Comment by dfilatov** [comment]
I don't see any reason why it shouldn't work with vidom. If you have not working REAL example attach it and reopen issue.

**Comment by rickardjanson** [comment]
@dfilatov  I don't know why you don't see it. Search your source code for `document.activeElement`

Can you find that word in your code? Answer NO!  Okey, meaning you are not supporting it.

If you had supported that, you would need to use document.activeElement. And you don't.

Search REACT source too, and you find this.

So no point to create example when it will not work. !!!

**Comment by rickardjanson** [comment]
@dfilatov If this are working in your code without use of `document.activeElement ` you are the only library that do that. And it\s not possible.

So, are you going to support this

**Comment by dfilatov** [comment]
I can't make head or tail of what your have written. You are writing so many words instead of simple example which proves your words.

**Comment by rickardjanson** [comment]
I understand things are very hard for you to understand. Look at this too: https://github.com/dfilatov/vidom/issues/64  First you should need to do is to update the DOM nodes.

**Comment by dfilatov** [comment]
I have give you answer in #64 but haven't seen any not working example here yet.

**Comment by rickardjanson** [comment]
I will come back to this later. Just now I'm analyzing your code line for line to find all your bugs :)

**Comment by dfilatov** [comment]
Oh, now I understand what you mean.

**Comment by dfilatov** [comment]
fixed, check

**Comment by rickardjanson** [comment]
verified!!

**Comment by rickardjanson** [comment]
@dfilatov I did a mistake. Sorry for that! I know there was something about this I should have remembered!! This is not solved.

Read this code from REACT:

```
/**
 * Same as document.activeElement but wraps in a try-catch block. In IE it is
 * not safe to call document.activeElement if there is nothing focused.
 *
 * The activeElement will be null only if the document body is not yet defined.
 */
function getActiveElement() /*?DOMElement*/ {
  try {
    return document.activeElement || document.body;
  } catch (e) {
    return document.body;
  }
}
```

**Comment by rickardjanson** [comment]
@dfilatov I know you are worried about performance, and `try/catch` is a killer. So this is a better solution:
```
function maintainFocus(previousActiveElement) {
        if (previousActiveElement && previousActiveElement != document.body && previousActiveElement != document.activeElement) {
            previousActiveElement.focus();
        }
    }
```

**Comment by dfilatov** [comment]
@rickardjanson I don't understand why I should you this. You need to provide not working case.
